backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
media_folder: theme/assets/images
public_folder: /assets/images
collections:
  - name: pages
    label: Pages
    identifier_field: title
    extension: md
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    folder: cms/pages
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Layout
        widget: hidden
        name: layout
        default: '{{slug}}.html'
      - &ref_0
        label: Seo
        name: seo
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: No index
            name: noindex
            widget: boolean
            default: false
            required: false
          - label: Open Graph Title
            name: og:title
            widget: string
            required: false
          - label: Open Graph Image
            name: og:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Twitter Title
            name: twitter:title
            widget: string
            default: summary
            required: false
          - label: Twitter Card
            name: twitter:card
            widget: string
            default: summary
            required: false
          - label: Twitter Site
            name: twitter:site
            widget: string
            required: false
          - label: Twitter Creator
            name: twitter:creator
            widget: string
            required: false
          - label: Additional HTML tags
            name: additional_tags
            widget: text
            required: false
  - name: kiing
    label: Profile
    folder: cms/kiing
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - hint: ''
        name: f_profile-picture
        label: Profile Picture
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_logo
        label: Logo
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_phone-number
        label: Phone Number
        widget: string
        required: false
      - hint: ''
        name: f_email-address
        label: Email Address
        widget: string
        required: false
      - hint: ''
        name: f_twitter
        label: Twitter
        widget: string
        required: false
      - hint: ''
        name: f_instagram
        label: Instagram
        widget: string
        required: false
      - hint: ''
        name: f_snapchat
        label: Snapchat
        widget: string
        required: false
      - hint: ''
        name: f_whatsapp
        label: Whatsapp
        widget: string
        required: false
      - hint: ''
        name: f_primary-colour
        label: Primary Colour
        widget: color
        required: false
        enableAlpha: true
        allowInput: true
      - hint: ''
        name: f_secondary-colour
        label: Secondary Colour
        widget: color
        required: false
        enableAlpha: true
        allowInput: true
      - hint: ''
        name: f_font-colour
        label: Font Colour
        widget: color
        required: false
        enableAlpha: true
        allowInput: true
      - hint: ''
        name: f_booking-form
        label: Booking Form
        widget: string
        required: false
      - hint: ''
        name: f_enquiries-form
        label: Enquiries Form
        widget: string
        required: false
      - label: Tags
        widget: hidden
        name: tags
        default: kiing
      - label: Layout
        widget: hidden
        name: layout
        default: '[kiing].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - name: links
    label: Links
    folder: cms/links
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Link Name
        widget: string
        required: true
      - hint: Place your target link here
        name: f_link
        label: Link
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - label: Tags
        widget: hidden
        name: tags
        default: links
      - label: Layout
        widget: hidden
        name: layout
        default: '[links].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - label: Theme Settings
    name: settings
    identifier_field: title
    extension: json
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    files:
      - label: General
        name: site
        file: cms/_data/settings/site.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: General
          - hint: Full domain url (needed for a correct sitemap file)
            name: domain
            label: Domain
            widget: string
            required: false
          - name: favicon
            label: Favicon
            widget: image
            allow_multiple: false
            required: false
          - name: apple_touch_icon
            label: Apple Touch Icon
            widget: image
            allow_multiple: false
            required: false
          - name: header_additional_content
            label: Additional Content Header
            hint: Content here will be placed before </head> tag
            widget: text
            required: false
          - name: footer_additional_content
            label: Additional Content Footer
            hint: Content here will be placed before </body> tag
            widget: text
            required: false
          - name: images_optimization
            label: Images Optimization
            widget: object
            collapsed: false
            fields:
              - label: Image Formats
                name: formats
                widget: select
                multiple: true
                options:
                  - label: Avif
                    value: avif
                  - label: Webp
                    value: webp
              - label: Image Dimensions
                name: dimensions
                widget: select
                multiple: true
                options:
                  - label: '500'
                    value: 500
                  - label: '800'
                    value: 800
                  - label: '1080'
                    value: 1080
                  - label: '1600'
                    value: 1600
                  - label: '2000'
                    value: 2000
                  - label: '2600'
                    value: 2600
      - label: Colors
        name: colors
        file: cms/_data/colors.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Colors
      - label: Texts
        name: texts
        file: cms/_data/texts.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Texts
          - hint: 'Original text: Bookings, key: 7b60675a'
            label: Text
            name: 7b60675a
            widget: string
          - hint: 'Original text: Collabs, key: -6430161a'
            label: Text
            name: '-6430161a'
            widget: string
          - hint: 'Original text: No items found., key: 3d503d2b'
            label: Text
            name: 3d503d2b
            widget: string
          - hint: >-
              Original text: Copyright 2022 Kiingswole.com - All rights
              reserved, key: -3c49f0c5
            label: Text
            name: '-3c49f0c5'
            widget: string
          - hint: 'Original text: Website, key: -53cd8785'
            label: Text
            name: '-53cd8785'
            widget: string
          - hint: 'Original text: Links, key: 4605f99'
            label: Text
            name: 4605f99
            widget: string
          - hint: 'Original text: Profile Details, key: -7f135175'
            label: Text
            name: '-7f135175'
            widget: string
          - hint: 'Original text: Account Info, key: 474de701'
            label: Text
            name: 474de701
            widget: string
          - hint: >-
              Original text: [vg_display_admin_page
              page_url="https://kiingswole.com/wp-admin/edit.php?post_type=links"],
              key: 25f56aa1
            label: Text
            name: 25f56aa1
            widget: text
          - hint: >-
              Original text: [vg_display_admin_page
              page_url="https://kiingswole.com/wp-admin/term.php?taxonomy=kiing&tag_ID=2&post_type=icons&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dkiing%26post_type%3Dicons"],
              key: 5dff16c6
            label: Text
            name: 5dff16c6
            widget: text
          - hint: >-
              Original text: [vg_display_admin_page
              page_url="https://kiingswole.com/wp-admin/profile.php"], key:
              -6888b2ee
            label: Text
            name: '-6888b2ee'
            widget: string
      - label: Links
        name: links
        file: cms/_data/links.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Links
          - hint: 'Original link: #, key: 23'
            label: Link
            name: '23'
            widget: string
          - hint: 'Original link: https://swrk.studio, key: -37bbd0e8'
            label: Link
            name: '-37bbd0e8'
            widget: string
          - hint: 'Original link: /, key: 2f'
            label: Link
            name: 2f
            widget: string
      - label: Images
        name: images
        file: cms/_data/images.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Images
          - label: Image
            name: 20108a0a
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 2ccee3b9
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 3313df35
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false